version: "3.8"

services:
  granteri-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - VAPI_API_KEY=${VAPI_API_KEY}
      - VAPI_PHONE_NUMBER_ID=${VAPI_PHONE_NUMBER_ID}
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - PORT=8000
      - HOST=0.0.0.0
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - granteri-agent
    restart: unless-stopped
    profiles:
      - production
